feat: add pre-commit check commitizen
radxa-docs/pre-commit-hooks pull request #8
Opened 2024-02-26 02:25 UTC by CodeChenL

* close https://github.com/radxa-docs/pre-commit-hooks/issues/4
  * close https://github.com/radxa-docs/pre-commit-hooks/issues/5

2024-02-26 02:27 UTC, CodeChenL commented
@RadxaYuntian

2024-02-26 04:08 UTC, RadxaYuntian commented
你这没有修复#4对应的脚本啊

2024-02-26 06:38 UTC, RadxaYuntian requested changes

2024-02-26 06:38 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
我们应该自定义一下传入的参数，而不是用他们的默认值。documentation那边有传入commit range

https://pre-commit.com/#pre-push

PRE_COMMIT_FROM_REF和PRE_COMMIT_TO_REF

2024-02-26 07:55 UTC, CodeChenL commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
你指的是commitizen-branch吗

2024-02-26 07:58 UTC, CodeChenL commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
```
    hooks:
      - id: commitizen
```
不就是检查本次commit吗

2024-02-26 08:15 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
我们check有这两个使用场景：
- 在git commit时检查commit message是否合规（这个应该用commitizen就可以）
- 在pr里检查commit message是否合规（这个可能在我们的ci环境执行会有问题：https://github.com/commitizen-tools/commitizen/blob/master/.pre-commit-hooks.yaml#L22）

第二个要验证一下

2024-02-26 08:16 UTC, CodeChenL commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
![image](https://github.com/radxa-docs/pre-commit-hooks/assets/43897062/f59bf12c-0551-479a-a741-a51602764903)
不知道我写的对不对

2024-02-26 08:23 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
变量有$

2024-02-26 08:23 UTC, CodeChenL commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
> 我们应该自定义一下传入的参数，而不是用他们的默认值。documentation那边有传入commit range
> 
> https://pre-commit.com/#pre-push
> 
> PRE_COMMIT_FROM_REF和PRE_COMMIT_TO_REF

这两个参数好像只有在push的时候有？

2024-02-26 08:28 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
反正就是pre-commit run的时候的环境，让这个能跑起来就行。我们ci就是执行这个命令的

2024-02-26 08:32 UTC, CodeChenL commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
目前测试结果：
1. pre-commit run -a不会报错（未运行commitizen）
2. commit和push时均可正常报错

2024-02-26 08:33 UTC, RadxaYuntian requested changes

2024-02-26 08:33 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +
我们之前都没有这些，为什么加上？

2024-02-26 08:33 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +          - push
应该是post-checkout stage：https://pre-commit.com/#post-checkout

2024-02-26 08:34 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +      - id: commitizen-branch
那你说我这里怎么触发：https://github.com/radxa-docs/documentation/blob/main/.github/workflows/deploy.yaml#L60

2024-02-26 08:35 UTC, CodeChenL commented on .pre-commit-config.yaml
> +
不加不触发，跟着https://github.com/commitizen-tools/commitizen/blob/f75eddcc1e69195a6edf07bfe7f75dbe6838361a/.pre-commit-config.yaml#L1加的

2024-02-26 08:36 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +
他们是他们，我们是我们。如果要触发就在hook对应的地方加上stage

2024-02-26 08:40 UTC, CodeChenL commented on .pre-commit-config.yaml
> +
可是去掉的花，commitizen就不触发了

2024-02-26 08:41 UTC, CodeChenL commented on .pre-commit-config.yaml
> +
这应该是他的依赖

2024-02-26 08:47 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +
```
default_install_hook_types:
  - pre-commit
  - commit-msg
```
应该就可以

2024-02-26 09:20 UTC, RadxaYuntian requested changes

2024-02-26 09:20 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +  - post-checkout
```suggestion
  - pre-push
```
还是改回pre-push好了，推的时候触发的确有必要
我们要修改documentation的CI,额外加一个test用--hook-stage来显式调用这个hook，默认的stage是commit

2024-02-26 09:20 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +
```suggestion
```
默认就是commit,不用重复定义

2024-02-26 09:20 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +          - post-checkout
```suggestion
          - pre-push
```
post-commit没有ref的输入，所以跳过

2024-02-26 09:22 UTC, RadxaYuntian commented
另外我才注意到这个是radxa-docs/pre-commit-hooks。这个hook其实是要放到documentation里面的，这个仓库只涉及我们自定义的hook。
现在这边加了弄好了直接复制到那边去

2024-02-26 09:25 UTC, CodeChenL commented
> 另外我才注意到这个是radxa-docs/pre-commit-hooks。这个hook其实是要放到documentation里面的，这个仓库只涉及我们自定义的hook。 现在这边加了弄好了直接复制到那边去

我想着是先加在这个仓库实验，也没坏处

2024-02-26 09:26 UTC, RadxaYuntian commented
是的，因为以后也要加到别的仓库里面去

2024-02-26 09:30 UTC, CodeChenL commented on .pre-commit-config.yaml
> +
不定义会报，今天早上的错

2024-02-26 10:10 UTC, RadxaYuntian reviewed
commitizen-branch在documentation那边测试过了么

2024-02-26 10:29 UTC, CodeChenL commented
> commitizen-branch在documentation那边测试过了么



> commitizen-branch在documentation那边测试过了么

提交和push没问题

2024-02-26 10:32 UTC, RadxaYuntian commented
我的意思是`pre-commit run --hook-stage push --from-ref FROM_REF --to-ref TO_REF`能检查历史commit消息么？

2024-02-26 11:51 UTC, RadxaYuntian commented
这边合并了documentation那边会以这边的实现为参考进行对比

2024-02-27 02:44 UTC, CodeChenL commented
使用自定义正则解决https://github.com/radxa-docs/pre-commit-hooks/issues/4

2024-02-27 03:22 UTC, RadxaYuntian requested changes

2024-02-27 03:22 UTC, RadxaYuntian commented on .cz.toml
别把所有的东西都放进来，只把我们自己修改过的部分留着。其他保持默认的就不要放进来

2024-02-27 04:02 UTC, RadxaYuntian requested changes

2024-02-27 04:02 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +    rev: v3.15.0 # automatically updated by Commitizen
```suggestion
    rev: v3.15.0
```
我们这边会不定期pre-commit update的，平常保证ci版本不变

2024-02-27 06:17 UTC, RadxaYuntian reviewed
squash

2024-02-27 07:23 UTC, RadxaYuntian approved these changes

2024-02-27 07:23 UTC, merged