feat: add pre-commit-hook check-chinese
radxa-docs/pre-commit-hooks pull request #9
Opened 2024-02-26 06:56 UTC by CodeChenL

close https://github.com/radxa-docs/pre-commit-hooks/issues/6

2024-02-26 06:59 UTC, CodeChenL commented
@RadxaYuntian It's ready for review

2024-02-26 07:04 UTC, RadxaYuntian requested changes

2024-02-26 07:04 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +    if grep -qP "[\p{Script=Han}]" "$1" && [[ "$1" == "i18n/en/docusaurus-plugin-content-docs/"* ]]; then
1. 这里路径是可以在调用者那里设定的
2. 看看其他文件的格式：https://github.com/radxa-docs/pre-commit-hooks/blob/main/pre_commit_hooks/disable-sidebar_label.sh

2024-02-26 07:26 UTC, RadxaYuntian requested changes

2024-02-26 07:26 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +    if grep -qP "[\p{Script=Han}]" "$2" && [[ "$2" == "$1"* ]]
直接用files指定的：https://pre-commit.com/#creating-new-hooks

2024-02-26 07:26 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +    if grep -qP "[\p{Script=Han}]" "$2" && [[ "$2" == "$1"* ]]
是在documentation那边设定范围

2024-02-26 07:40 UTC, CodeChenL commented on .pre-commit-config.yaml
> +  - repo: local
这里用于测试，合并前去掉

2024-02-27 08:18 UTC, RadxaYuntian commented
![image](https://github.com/radxa-docs/pre-commit-hooks/assets/95260730/e932be98-b37a-476e-a734-3b6e190821d1)
所以你以为perf是什么别的意思么

2024-02-27 08:29 UTC, CodeChenL commented
> ![image](https://private-user-images.githubusercontent.com/95260730/308089543-e932be98-b37a-476e-a734-3b6e190821d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjI3NTksIm5iZiI6MTcwOTAyMjQ1OSwicGF0aCI6Ii85NTI2MDczMC8zMDgwODk1NDMtZTkzMmJlOTgtYjM3YS00NzZlLWE3MzQtM2I2ZTE5MDgyMWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA4MjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Y2U5OTljNjI5MzRkZDUyNWNmZDM5NWQ5MmRlZTE1NjNkYzcyNTM5NGRjYTkxMzlkZWNiMTIzNjljZjUwMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf3KgWgTBdoh5I_BsTgcPb4UHN47t6fzqqBfAgcBdrw) 所以你以为perf是什么别的意思么

好吧，我看的别的文章理解成优化代码的意思了

2024-02-27 08:38 UTC, RadxaYuntian commented
一般就是feat和fix

2024-02-27 08:42 UTC, CodeChenL commented
> 一般就是feat和fix

了解了，所以对于代码还有什么审阅意见吗

2024-02-27 08:53 UTC, RadxaYuntian requested changes
看看其他的脚本的代码风格，确保一致

2024-02-27 08:53 UTC, RadxaYuntian commented on .pre-commit-config.yaml
> +        types: [markdown]
你本地测试这些重复的都不需要

2024-02-27 08:53 UTC, RadxaYuntian requested changes

2024-02-27 08:53 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +    if grep -qP "[\p{Script=Han}]" "$1"
```suggestion
    if grep -qP "[\p{Script=Han}]" "$1" >/dev/null
```

2024-02-27 08:58 UTC, CodeChenL commented
> 看看其他的脚本的代码风格，确保一致

我看也没什么区别呀，要加注释和自动修正文件吗

2024-02-27 09:11 UTC, RadxaYuntian requested changes
你最开始的版本还有些缩进和[[]]的问题

2024-02-27 09:11 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +    if grep -qP "[\p{Script=Han}]" "$1" >/dev/null
功能注释：https://github.com/radxa-docs/pre-commit-hooks/blob/main/pre_commit_hooks/check-folder-structure.sh#L6

2024-02-27 09:11 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +        echo "Error: File '$1' contains Chinese characters and it's English documents." >&2
错误消息格式：https://github.com/radxa-docs/pre-commit-hooks/blob/main/pre_commit_hooks/check-folder-structure.sh#L10

2024-02-27 09:11 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +        ret=1
先赋值再提示

2024-02-27 09:11 UTC, RadxaYuntian requested changes
你最开始的版本还有些缩进和[[]]的问题

2024-02-27 09:12 UTC, RadxaYuntian commented
你这个参杂中文没有什么很明显正确的修复方式，就不用做这个

2024-02-27 09:18 UTC, RadxaYuntian requested changes

2024-02-27 09:18 UTC, RadxaYuntian commented on pre_commit_hooks/check-chinese.sh
> +    if grep -qP "[\p{Script=Han}]" "$1"
重定向没了

2024-02-27 09:21 UTC, RadxaYuntian commented
另外这边的PR不要关闭issue，只是链接上就好。在documentation那边合并了再关

2024-02-27 09:24 UTC, CodeChenL commented
> 另外这边的PR不要关闭issue，只是链接上就好。在documentation那边声明close这边的issue

已更新pr信息

2024-02-27 09:40 UTC, RadxaYuntian reviewed
squash

2024-02-27 10:07 UTC, RadxaYuntian approved these changes

2024-02-27 10:07 UTC, merged